[package]
name = "pow-rs"
version = "1.0.1"
edition = "2024"

[lib]
name = "pow"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = "0.3"
sha2 = "0.10"
hex = "0.4"